apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devopstales-catalog
  namespace: olm
spec:
  displayName: devopstales
  publisher: devopstales
  sourceType: grpc
  image: danielepalaia/operatorhub-cluster-operator-index:1.14.0 
  updateStrategy:
    registryPoll:
      interval: 1m
