apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trivy-operator
  namespace: rabbitmq-system 
spec:
  channel: stable 
  installPlanApproval: Automatic
  name: rabbitmq-operator
  source: devopstales-catalog
  sourceNamespace: olm
  startingCSV: rabbitmq-cluster-operator.v1.14.0 
